//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBanakMVC2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DonationRecords
    {
        public int ID { get; set; }
        public string DonorName { get; set; }
        public string AcceptorName { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
