//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBanakMVC2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userRegistration()
        {
            this.tbl_userPost = new HashSet<tbl_userPost>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string Criterias { get; set; }
        public string BloodGroup { get; set; }
        public string Sub_District { get; set; }
        public string Union_council { get; set; }
        public string Village { get; set; }
        public Nullable<System.DateTime> Last_donation_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_userPost> tbl_userPost { get; set; }
    }
}
