//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBanakMVC2.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class userPost
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Division { get; set; }
        public string District { get; set; }
        public string Thana { get; set; }
        public string Unian { get; set; }
        public string Village { get; set; }
        public string Message { get; set; }
        public string BloodGroup { get; set; }
    }
}
